name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    concurrency:
      group: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set dryRun to true
        run: |
          cat default.json | jq --arg dryRun true '. + {dryRun: $dryRun}' > default-dry-run.json

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.66.6
        with:
          configurationFile: default-dry-run.json
          token: ${{ secrets.RENOVATE_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.66.6
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_TOKEN }}
